<?php error_reporting(0); ?>
<link href="css/table_white.css" rel="stylesheet">	
<SCRIPT language=JavaScript>
function reload(form)
{
var val=form.fa.options[form.fa.options.selectedIndex].value;
self.location='?&q=' + val;
}
</script>
<script>function Print() {
document.body.offsetHeight;
window.print();
}
</script>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<form name="form2" method="post" onSubmit="Print()" action="">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="Submit2" type="submit" class="button" value="PRINT">


<div align='center'>
<form action="" method="post">
<select name="fa" id="fa" onChange="reload(this.form)">
<option value="" > --- PILIH SATKER --- </option>
<option value ="KANTOR PUSAT DIREKTORAT JENDERAL PERBENDAHARAAN"> KANTOR PUSAT DIREKTORAT JENDERAL PERBENDAHARAAN </option>
<option value ="SISTEM PERBENDAHARAAN DAN ANGGARAN NEGARA"> SISTEM PERBENDAHARAAN DAN ANGGARAN NEGARA </option>
<option value ="KOMITE STANDAR AKUNTASI PEMERINTAH (KSAP)"> KOMITE STANDAR AKUNTASI PEMERINTAH (KSAP) </option>
<option value ="BADAN PENGELOLA DANA PERKEBUNAN KELAPA SAWIT"> BADAN PENGELOLA DANA PERKEBUNAN KELAPA SAWIT </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI ACEH"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI ACEH --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAPAK TUAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAPAK TUAN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAKENGON"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAKENGON </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEULABOH"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEULABOH </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LHOK SEUMAWE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LHOK SEUMAWE </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LANGSA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LANGSA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUTACANE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUTACANE </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDA ACEH"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDA ACEH </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA UTARA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA UTARA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TEBING TINGGI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TEBING TINGGI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG BALAI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG BALAI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIDIKALANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIDIKALANG</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIBOLGA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIBOLGA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA RANTAU PRAPAT"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA RANTAU PRAPAT </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEMATANG SIANTAR</option>"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEMATANG SIANTAR</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PADANG SIDEMPUAN</option>"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PADANG SIDEMPUAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEDAN II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEDAN II</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEDAN I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MEDAN I </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA GUNUNG SITOLI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA GUNUNG SITOLI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BALIGE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BALIGE</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SOLOK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SOLOK </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIJUNJUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIJUNJUNG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PAINAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PAINAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PADANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PADANG</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUBUK SIKAPING"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUBUK SIKAPING</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BUKITTINGGI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BUKITTINGGI </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI RIAU"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI RIAU --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA RENGAT"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA RENGAT</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEKANBARU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEKANBARU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA DUMAI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA DUMAI </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI KEPULAUAN RIAU"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI KEPULAUAN RIAU --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG PINANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG PINANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BATAM"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BATAM</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI JAMBI"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI JAMBI --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUNGAI PENUH"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUNGAI PENUH</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MUARA BUNGO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MUARA BUNGO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUALA TUNGKAL"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUALA TUNGKAL </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAMBI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAMBI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANGKO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANGKO</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA SELATAN"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SUMATERA SELATAN --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEKAYU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEKAYU</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALEMBANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALEMBANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUBUK LINGGAU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUBUK LINGGAU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LAHAT"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LAHAT </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BATURAJA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BATURAJA</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI LAMPUNG"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI LAMPUNG --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA METRO LAMPUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA METRO LAMPUNG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LIWA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LIWA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTABUMI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTABUMI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDAR LAMPUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDAR LAMPUNG</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI BENGKULU"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI BENGKULU --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MUKO MUKO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MUKO MUKO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANNA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANNA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA CURUP"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA CURUP </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BENGKULU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BENGKULU</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI BANGKA BELITUNG"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI BANGKA BELITUNG --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG PANDAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG PANDAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PANGKAL PINANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PANGKAL PINANG</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI BANTEN"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI BANTEN --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANGERANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANGERANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SERANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SERANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA RANGKASBITUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA RANGKASBITUNG </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI DKI JAKARTA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI DKI JAKARTA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS PINJAMAN DAN HIBAH</option>"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS PINJAMAN DAN HIBAH</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS PENERIMAAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS PENERIMAAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS INVESTASI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KHUSUS INVESTASI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA VII"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA VII</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA VI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA VI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA V"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA V</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA IV"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA IV </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA III"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA III</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA II </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAKARTA I</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TASIKMALAYA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TASIKMALAYA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUMEDANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUMEDANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUKABUMI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUKABUMI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWAKARTA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWAKARTA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUNINGAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUNINGAN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KARAWANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KARAWANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA GARUT"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA GARUT</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA CIREBON"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA CIREBON</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BOGOR"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BOGOR</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BEKASI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BEKASI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDUNG II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDUNG II </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDUNG I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANDUNG I</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA TENGAH"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA TENGAH --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TEGAL"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TEGAL</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURAKARTA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURAKARTA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SRAGEN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SRAGEN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEMARANG II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEMARANG II</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEMARANG I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SEMARANG I </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWOREJO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWOREJO</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWOKERTO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWOKERTO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWODADI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PURWODADI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEKALONGAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PEKALONGAN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PATI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PATI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAGELANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAGELANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUDUS"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUDUS</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KLATEN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KLATEN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA CILACAP"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA CILACAP</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANJARNEGARA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANJARNEGARA </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI D.I. YOGYAKARTA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI D.I. YOGYAKARTA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA YOGYAKARTA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA YOGYAKARTA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA WONOSARI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA WONOSARI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA WATES"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA WATES</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA TIMUR"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI JAWA TIMUR --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TUBAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TUBAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURABAYA II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURABAYA II</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURABAYA I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SURABAYA I </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIDOARJO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SIDOARJO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PAMEKASAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PAMEKASAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PACITAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PACITAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MOJOKERTO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MOJOKERTO</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MALANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MALANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MADIUN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MADIUN </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KEDIRI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KEDIRI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JEMBER"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JEMBER </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BONDOWOSO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BONDOWOSO</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BOJONEGORO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BOJONEGORO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BLITAR"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BLITAR </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANYUWANGI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANYUWANGI </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINTANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINTANG</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINGKAWANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINGKAWANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SANGGAU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SANGGAU</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PUTUSSIBAU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PUTUSSIBAU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PONTIANAK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PONTIANAK</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KETAPANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KETAPANG </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN TENGAH"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN TENGAH --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAMPIT"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAMPIT </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PANGKALAN BUN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PANGKALAN BUN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALANGKARAYA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALANGKARAYA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BUNTOK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BUNTOK </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN SELATAN"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN SELATAN --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PELAIHARI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PELAIHARI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTABARU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTABARU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BARABAI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BARABAI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANJARMASIN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANJARMASIN</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN TIMUR"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI KALIMANTAN TIMUR --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TARAKAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TARAKAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG REDEP"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TANJUNG REDEP</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAMARINDA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAMARINDA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA NUNUKAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA NUNUKAN</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BALIKPAPAN"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BALIKPAPAN </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI BALI"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI BALI --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINGARAJA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINGARAJA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA DENPASAR"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA DENPASAR </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA AMLAPURA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA AMLAPURA </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI NUSA TENGGARA BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI NUSA TENGGARA BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUMBAWA BESAR"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SUMBAWA BESAR</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SELONG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SELONG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MATARAM"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MATARAM</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BIMA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BIMA </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI NUSA TENGGARA TIMUR"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI NUSA TENGGARA TIMUR --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA WAINGAPU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA WAINGAPU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA RUTENG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA RUTENG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LARANTUKA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LARANTUKA</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUPANG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KUPANG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA ENDE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA ENDE </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA ATAMBUA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA ATAMBUA</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI SELATAN"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI SELATAN --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA WATAMPONE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA WATAMPONE</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINJAI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SINJAI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PARE PARE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PARE PARE</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALOPO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALOPO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKASSAR II"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKASSAR II</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKASAR I"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKASAR I</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKALE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAKALE </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BENTENG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BENTENG</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANTAENG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BANTAENG </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI TENGAH"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI TENGAH --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TOLI TOLI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TOLI TOLI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA POSO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA POSO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA PALU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUWUK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA LUWUK</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAMUJU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAMUJU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAJENE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MAJENE </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI TENGGARA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI TENGGARA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA RAHA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA RAHA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOLAKA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOLAKA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KENDARI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KENDARI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BAU BAU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BAU BAU</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI GORONTALO"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI GORONTALO --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MARISA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MARISA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA GORONTALO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA GORONTALO</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI UTARA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI SULAWESI UTARA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAHUNA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TAHUNA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANADO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANADO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTAMUBAGU"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA KOTAMUBAGU </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BITUNG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BITUNG </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI MALUKU UTARA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI MALUKU UTARA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TOBELO"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TOBELO </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TERNATE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TERNATE</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI MALUKU"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI MALUKU --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TUAL"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TUAL </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAUMLAKI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SAUMLAKI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MASOHI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MASOHI </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA AMBON"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA AMBON</option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI PAPUA"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI PAPUA --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA WAMENA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA WAMENA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA TIMIKA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA TIMIKA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SERUI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SERUI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA NABIRE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA NABIRE </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MERAUKE"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MERAUKE</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAYAPURA"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA JAYAPURA </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA BIAK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA BIAK </option>

<optgroup><option value ="KANWIL DITJEN PERBENDAHARAAN PROVINSI PAPUA BARAT"> --- KANWIL DITJEN PERBENDAHARAAN PROVINSI PAPUA BARAT --- </option></optgroup>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA SORONG"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA SORONG </option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANOKWARI"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA MANOKWARI</option>
<option value ="KANTOR PELAYANAN PERBENDAHARAAN NEGARA FAK FAK"> KANTOR PELAYANAN PERBENDAHARAAN NEGARA FAK FAK</option>
  </select></div>
<br><br>
<?php 
error_reporting(0);
include "koneksi2.php";
$today = gmdate("d-m-y", time()+60*60*8); 
if (isset($_GET['q'])) $nmsatker= $_GET['q'];

$sql  = oci_parse($conn, "select * from (
select b.nm_satker, to_char(a.tgluploadsakti,'dd-mm-yyyy hh:mi:ss') tgluploadsakti, a.email_user, a.namafilesakti from (
select  satkeroffice_id, tgluploadsakti, createby email_user, namafilesakti from  POR_T_ADK where STATUSADK_ID='2' AND deleted IS NULL) a left join
(select distinct id, nm_satker from POR_R_SATKEROFFICE) b on a.satkeroffice_id=b.id) where nm_satker='$nmsatker' order by tgluploadsakti desc" );

oci_execute($sql);

if ($nmsatker!='') {

echo "
<table height='50px' width='1298px' style='background:white;' align='center' border='0'>
<tr border='0' height='30px'><td colspan='5'align='center'>&nbsp;</td></tr>
<tr><td colspan='5'align='left'></td></tr>
<tr><td colspan='5' align='center'><strong>PENGIRIMAN/UPLOAD ADK SAKTI KE PORTAL SPAN</strong></td></tr>
<tr border='0'><td colspan='5' align='center'><strong>". $nmsatker ."</strong></td></tr>
<tr border='0' height='30px' align='left'><td colspan='6' align='left'>&nbsp;Tanggal : ".$today."</td></tr>
</table>
<table  width='1300px' align='center' border='1'>
<tbody>
    <tr><th align='center'><strong>No. </strong></th><th>Nama Satker</th><th>Tanggal dan Jam</th><th>Email Pengguna</th><th>Nama File</th></tr>";
$no = 1;
while (($row1 = oci_fetch_array($sql, OCI_BOTH)) != false) {
    // Use the uppercase column names for the associative array indices
 echo     "
  <tr class='gradeX'>
    	 <td>$no.</td>  
    <td>". $row1["NM_SATKER"] . "</td>
    <td>". $row1["TGLUPLOADSAKTI"] . "</td>
    <td>". $row1["EMAIL_USER"] . "</td>
    <td>". $row1["NAMAFILESAKTI"] . "</td>
  </tr>
 ";
    $no++; 
}
echo "</tbody>
</table>
</div>
</div>
";
}
else{};
oci_free_statement($sql);
oci_close($conn);
?>